spring:
  datasource:
    # Trên Render, có thể truyền biến DATABASE_URL từ tab Environment
    url: ${DATABASE_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    # Tắt log SQL để đỡ tốn bộ nhớ và log file không bị phình to
    show-sql: false 
    properties:
      hibernate:
        format_sql: false
        hbm2ddl.create_namespaces: true

app:
  storage:
    type: s3 # Trên prod sẽ tự động lưu ảnh lên S3 (hoặc Cloudinary)

# Có thể ẩn swagger trên production nếu muốn bảo mật
# springdoc:
#   swagger-ui:
#     enabled: false
